/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.empleadosGUI;
import java.awt.Graphics;
import java.awt.Image;
import java.io.File;
import sistema.empleadosDAL.conexion;  //PRIMERO IMPORTAMOS LA CONEXION A LA BASE DE DATOS
import java.sql.*;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sistema.empleadosBL.empleadosBL;

/**
 *
 * @author pc
 */
public class frmEmpleados extends javax.swing.JFrame {
 DefaultTableModel modelo;  //Poner en forma de columnas bien ordenado en la tabla, modelo es la tabla
 /* FondoPanel fondo=new FondoPanel();*/
    public frmEmpleados() {
        initComponents();
      /* this.setContentPane(fondo);*/
        String titulo[]={"ID","Nombre","Correo" };
        modelo=new DefaultTableModel(null,titulo);
        tblEmpleados.setModel(modelo); //en la tabla agregamos la nueva modalidad de tabla modelo
        
        this.mostrarDatosEnTabla();
        this.limpiar();
        setIconImage(new ImageIcon(getClass().getResource("logo.png")).getImage());
       this.setLocationRelativeTo(null);
     //  this.setResizable(false);
       this.setTitle("Carga de datos Empleados");
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEmpleados = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtID = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        fondoVentana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblEmpleados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblEmpleadosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblEmpleados);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 210, 370, 120));

        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/anadir-lista.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.setMaximumSize(new java.awt.Dimension(60, 23));
        btnAgregar.setMinimumSize(new java.awt.Dimension(60, 23));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 90, 30));

        btnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/editar (2).png"))); // NOI18N
        btnEditar.setText("Editar");
        btnEditar.setMaximumSize(new java.awt.Dimension(85, 23));
        btnEditar.setMinimumSize(new java.awt.Dimension(85, 23));
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 80, 30));

        btnBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/goma-de-borrar.png"))); // NOI18N
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 170, 80, 30));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/recursos/navegador.png"))); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 90, 30));

        txtID.setEditable(false);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 94, -1));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 360, -1));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 132, 360, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ID:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Nombre:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Correo:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 112, -1, -1));

        fondoVentana.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sistema/empleadosGUI/carga datos.jpg"))); // NOI18N
        fondoVentana.setText("jLabel4");
        getContentPane().add(fondoVentana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 330));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        conexion objeConexion=new conexion();
    

        empleadosBL empl=recuperarDatosGUI(); //PARA TENER MÁS CONTROL
                 String srtSentenciaInsert=String.format("insert into Empleados (ID,Nombre,Correo) "
                        + "values (null,'%s','%s')",empl.getNombre(),empl.getCorreo());

                  objeConexion.ejecutarSentenciaSQL(srtSentenciaInsert);
                  this.mostrarDatosEnTabla();
               
                  this.limpiar();
        
    }//GEN-LAST:event_btnAgregarActionPerformed
//RECUPERAR DATOS DEL JTABLE
    private void tblEmpleadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblEmpleadosMouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==1){ //Si el usuario dio click en la region
            
            JTable receptor=(JTable)evt.getSource();//TODO LOS ID,NOMBRE,CORREO VAN A PARAR AL RECEPTOR, LO CONVERTIMOS
            //PRIMERO A JTTABLE, LO CASTEAMOS
            txtID.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),0).toString());
            txtNombre.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),1).toString());
            txtCorreo.setText(receptor.getModel().getValueAt(receptor.getSelectedRow(),2).toString());
        }
         btnAgregar.setEnabled(false);
        btnBorrar.setEnabled(true);
        btnEditar.setEnabled(true);
    }//GEN-LAST:event_tblEmpleadosMouseClicked

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
               conexion objeConexion=new conexion();
    

        empleadosBL empl=recuperarDatosGUI(); //PARA TENER MÁS CONTROL
                 String srtSentenciaInsert=String.format("DELETE FROM Empleados where ID=   %d",empl.getID());
                 //el d hace referencia al identificador númerico ID

                  objeConexion.ejecutarSentenciaSQL(srtSentenciaInsert);
                 this.mostrarDatosEnTabla();
                 this.limpiar();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
              conexion objeConexion=new conexion();
    

        empleadosBL empl=recuperarDatosGUI(); //PARA TENER MÁS CONTROL
                 String srtSentenciaInsert=String.format("UPDATE Empleados SET Nombre='%s',"
                         + "Correo='%s' where ID=%d ",empl.getNombre(),empl.getCorreo(),empl.getID());
                 
                  objeConexion.ejecutarSentenciaSQL(srtSentenciaInsert);
        this.mostrarDatosEnTabla();
        this.limpiar();
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
       this.limpiar();
    }//GEN-LAST:event_btnCancelarActionPerformed
       
  public void mostrarDatosEnTabla(){
      //EN EL BOTON BORRAR , BORRA LA FILA SELECCIONADA
      while(modelo.getRowCount()>0){
          modelo.removeRow(0);
      }
       conexion objeConexion=new conexion();
       
                    try {
            //Me conecto con la tabla Empleados
            ResultSet resultado=objeConexion.consultarRegistros("Select * from Empleados");
            //Devuelvo resultados
            while(resultado.next()){
                
                //accedemos a los campos
                System.out.println(resultado.getString("ID"));
                System.out.println(resultado.getString("Nombre"));
                System.out.println(resultado.getString("Correo"));
                
                Object user[]={resultado.getString("ID"),resultado.getString("Nombre"),resultado.getString("Correo")};
                
                modelo.addRow(user);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
  }
//PARA RECUPERAR INFORMACIÓN QUE SE INGRESA EN LOS TEXTFIELD ID,NOMBRE,CORREO   
    public empleadosBL recuperarDatosGUI(){
         empleadosBL empl=new empleadosBL();
         
         int ID=(txtID.getText().isEmpty()?0:Integer.parseInt(txtID.getText()));
         
         empl.setID(ID);
         empl.setNombre(txtNombre.getText());
         
         empl.setCorreo(txtCorreo.getText());
         
         return empl;
        }
    public void limpiar(){
        
        txtID.setText("");
        txtNombre.setText("");
        txtCorreo.setText("");
        
        btnAgregar.setEnabled(true);
        btnBorrar.setEnabled(false);
        btnEditar.setEnabled(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmEmpleados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmEmpleados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel fondoVentana;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEmpleados;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
/* class FondoPanel extends JPanel{
     private Image imagen;
     
     public void paint(Graphics g){
         imagen=new ImageIcon(getClass().getResource("carga datos.jpg")).getImage();
         
         g.drawImage(imagen, 0, 0, getWidth(),getHeight(),this);
         
         setOpaque(false);
         super.paint(g);
     }
 }*/
       

}
